package android.gameengine.icadroids.tiles;

/**
 * Every tile in a tilemap is a tile object. You can manipulate the tile by
 * using its methods.
 * 
 * Note: tile objects will be automatically generated by GameTiles
 * 
 * @author Bas van der Zandt
 * 
 */
public class Tile {

	private int tileType;
	/**
	 * The position of the tiles in the tilemap. This is NOT the x and y
	 * position in the game world!
	 */
	protected int tileNumberX, tileNumberY;
	/**
	 * This tile object is instance of this gameTiles object
	 */
	protected GameTiles gameTiles;

	/**
	 * Every tile has a tiletype and is a instance of an gameTiles object.
	 * Tiletype lower than 0 means invisible.
	 * 
	 * @param tileType
	 * @param gameTiles
	 */
	public Tile(int tileType, GameTiles gameTiles) {
		super();
		this.tileType = tileType;
		this.gameTiles = gameTiles;
	}

	/**
	 * Change the tile type
	 * 
	 * @param tileType
	 *            the new tiletype
	 */
	public void setTileType(int tileType) {
		this.tileType = tileType;
	}

	/**
	 * Get the tile tiletype
	 * 
	 * @return the tiletype
	 */
	public int getTileType() {
		return tileType;
	}

	/**
	 * Get the x tile number <b> in the tile map </b>
	 * 
	 * @return The x tile number
	 */
	public int getTileNumberX() {
		return tileNumberX;
	}

	/**
	 * Get the y tile number <b> in the tile map </b>
	 * 
	 * @return The y tile number
	 */
	public int getTileNumberY() {
		return tileNumberY;
	}

	/**
	 * Get the instance of gameTiles where this Tile is a instance from
	 * 
	 * @return gameTile object
	 */
	public GameTiles getGameTiles() {
		return gameTiles;
	}

	/**
	 * Get the x position of the tile Note: x and y values are at the top left
	 * corner of the tile
	 * 
	 * @return the x position in the game world
	 */
	public int getTileX() {
		return tileNumberX * gameTiles.tileSize;
	}

	/**
	 * get the y position of the tile Note: x and y values are at the top left
	 * corner of the tile
	 * 
	 * @return the y position in the game world
	 */
	public int getTileY() {
		return tileNumberY * gameTiles.tileSize;
	}

}
